FROM node:18

# Set working directory
WORKDIR /frontend

# Install dependencies
# RUN npm install --package-lock-only
COPY package.json /frontend/package.json
# RUN npm ci

RUN npm install --silent
RUN npm install react-scripts@5.0.0 -g --silent

# Copy the application code
COPY . ./

# Expose the port
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]