FROM node:18

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the application code
COPY . ./

# Expose the port
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]
